### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by kistonw** [qhlai/openwrt-nanopi-actions#1]
![Screenshot_2021-01-04-08-30-09-960_com kiwibrowser browser](https://user-images.githubusercontent.com/45121508/103492656-f5ba0c80-4df1-11eb-9fa6-5f32e0ac3bcb.jpg)

**Comment by qhlai** [comment]
这个不算编译错误，固件上传到release出错了，没tag，前面的上传固件应该能用，直接去前面给的链接拿固件。
tag的问题我10号再修。

**Comment by qhlai** [comment]
![图片](https://user-images.githubusercontent.com/43923153/103613436-8531fd80-4f61-11eb-8932-f6f5a52c16d0.png)
![图片](https://user-images.githubusercontent.com/43923153/103613547-ae528e00-4f61-11eb-9c82-66042607ac7e.png)

**Comment by kistonw** [comment]
好的 大佬

**Comment by qhlai** [comment]
应该修完了，顺便整理了下结构，neo2的源码库不知道现在哪个好，你可以改改试试。默认不release了，没啥用。

**Comment by qhlai** [comment]
结束
